# Generated by Django 5.0.1 on 2024-01-11 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("current_date", models.DateTimeField(auto_now_add=True)),
                ("assign_date", models.DateTimeField()),
                ("balance", models.IntegerField()),
                ("category", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("debit", models.IntegerField()),
                ("credit", models.IntegerField()),
                ("m_of_pay", models.CharField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
