# Generated by Django 5.0.1 on 2024-01-11 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0003_alter_account_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["updated", "created"]},
        ),
        migrations.RenameField(
            model_name="account",
            old_name="current_date",
            new_name="created",
        ),
    ]
